# strongSwan swanctl.conf for SITE-B (mirror of siteA with IPs swapped)

connections {

    site-b-to-a {

        version = 2
        local_addrs  = 172.20.0.20    # OUR IP
        remote_addrs = 172.20.0.10    # siteA's IP

        proposals = aes256-sha256-modp2048

        local {
            auth = pubkey
            certs = siteB.crt
            id = 172.20.0.20
        }

        remote {
            auth = pubkey
            id = 172.20.0.10
        }

        children {
            tunnel {
                esp_proposals = aes256gcm128
                mode = tunnel
                local_ts  = 10.0.1.0/24    # siteB's LAN
                remote_ts = 10.0.0.0/24    # siteA's LAN
                start_action = start
            }
        }
    }
}

secrets {
    private-siteB {
        file = siteB.key
    }
}
